name: Aural-player swift build and test (dummy)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    name: prepare-job
    runs-on: macos-10.15
       
  build:
    name: build-job
    needs: prepare
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: #swift build -v
    
    
  tests: 
    name: test-job
    needs: build  
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: #swift test -v
